src/Account/Account.js, src/Account/_initializeAccount.js, src/Account/getWorker.js, src/Account/hasPlugins.js, src/plugins/Workers/BIP44Worker.js
While setting these plugins together will do what we expect from them (aka : Keeping 20 unused address in our pool), on first execution, however, only the 20 first will be fetched (as BIP44 do not know yet if they are used or not). 
We therefore need to have a recursive interaction between them to ensure on start enought addresses.
- Feat : Added methods in Account `hasPlugins`, `getWorker`
- Impr : initializeAccount will recursively check for both enough addresses + fetch data from network.
Fixes DPW-710, makes initializeAccount longer depending on walletHistory.
Might require refactoring later and may be a timeout force exit (to avoid getting stuck there in case of bad connectivity ?)
=> feat: Allow BIP44Worker and SyncWorker to work together

README.md, examples/wallet-dapi-porto-update.js, package-lock.json, package.json, src/Account/fetchAddressInfo.js, src/transports/Transporter.js
We recently lost any ability to restore the Maitai Devnet, therefore we need to switch to the Porto Devnet. 
This P.R intend to provide the support. 
- Chore : 
- Updated package + added DPP
- Fix : 
- Updated UTXO parsing
- Updated default DAPI IP. 
- Breaking : 
- Insight-client won't work anymore.
Breaking change : We dropped support for Insight-Client long time ago, but this PR will officially put itself unable to process UTXO. There is no plan to put that feature into the MVP, but PR will be reviewed with pleasure :) 
Also, congratz and thanks to the @dashevo/backend team for having made Porto reach stable pre-rc state !
=> feat: Migrate to Porto devnet

.eslintrc, .travis.yml, package-lock.json, package.json
Due to the fact that we embed Wallet-lib in some specific context that are caring about size (react-native wallet). 
And the fact that any changes to Global can actually cause some duplicates (for instant : let's think about dashevo/dashcore-lib), monitoring library file changes allow us to notice any further issues.
- Installed `size-limit`
- Added two scripts : 
- `size` : Will test the loading time, running time and execution time and test it against package.json definitions
- `size:why` : Will run the above script and will also allow to explain why (see embedded picture).
- SizeLimit allow us to know the size, download time and execution time.
- More info : https://github.com/ai/size-limit
- We also will not limit in any means our features because of size limit. But we want to lower …
=> chore: Added size limit as part of CI

src/Account/injectPlugin.js, src/plugins/DAP.js
Right now, it would be required to a develop to handle the verification of it's dap against the network by itself. However, using standardized transporter, we know the method `fetchContract` is required and present. 
Therefore we can automate the verification of a DAP directly in the start up process. This only requires to a DAP maker to pass `schema:` as an argument (see screenshot below). 
We also needed a registration method as handler for DAP maker. 
- added DAP registration
- added DAP verification directly into DAP.js
- when a plugin is a DAP, will add verification as part of the process.
=> feat: Added DAP Verification/Registration on WLib startup

examples/daps/DAPDoc.js, examples/daps/DashPayDAP.js, examples/stdPlugins/MasternodeUpdater.js, examples/wallet-dapi-fromHDPubKey.js, examples/wallet-dapi-porto-update.js, package-lock.json, package.json, src/KeyChain.js, src/Storage/Storage.js, src/Wallet/getAccount.js, src/plugins/DAP.js, src/plugins/Worker.js, src/plugins/Workers/ChainWorker.js, src/plugins/Workers/SyncWorker.js, src/transports/Insight/insightClient.js, src/transports/Transporter.js, src/utils/mnemonic.js, test/Account/createTransaction.js, test/KeyChain.js, test/Storage/getTransaction.js, test/Storage/startWorker.js, test/Wallet/Wallet.js, test/Wallet/fromMnemonic.js, test/transports/Transporter.js
We need to limit access of keychain from plugins. We therefore add `getHardenedFeaturePath` to start from, to most of derivation needs.
- feat: added getHardenedFeaturePath method
- test for Keychain (more would be welcomed)
This is a first PR toward improving safety of the keychain and limiting access from plugins and dependencies.
Most of the time, what all user of the keychain is to derivate for public or private key. 
They all ends up doing the first same derivation but starting with the master key. 
We will need to move toward this new method in a later update.
=> feat(KeyChain): added getHardenedFeaturePath

package.json, src/Account/_initializeAccount.js, src/plugins/Workers/SyncWorker.js, src/transports/Transporter.js, test/transports/Transporter.js
- Breaking change in DAPI-Client removed `getTransaction` alias for `getTransactionById` 
- Modified instance of `getTransaction` for `getTransactionById`
=> chore(dapi-client): bump to 0.6.2 + adapt getTransaction

package-lock.json, package.json
One of the DAPI node is buggy. For short-term, we push that to refer to a branch without the issue. 
- Refer to branch `temp/exclusion`
=> chore(package): refer to branch with hardcoded excluded ip.

examples/wallet-dapi-fromHDPubKey.js, examples/wallet-insight-smartrug.js, src/Account/Account.js, src/Account/createTransaction.js, src/Account/getBIP44Path.js, src/Account/getNetwork.js, src/Storage/Storage.js, src/Storage/createWallet.js, src/Storage/updateAddress.js, src/Wallet/Wallet.js, src/Wallet/updateNetwork.js, src/utils/is.js, test/Account/getBalance.js, test/Storage/Storage.js, test/Storage/createWallet.js, test/Wallet/Wallet.js, test/Wallet/fromHDPublicKey.js, test/Wallet/updateNetwork.js, test/fixtures/walletStore.json, test/utils/index.js
Dashcore Lib has a Network prototype, we relied on it as a input of the network parameters in `Wallet`, `Account` and `updateNetwork` methods. 
Starting from there, Wallet-lib will not be an helper on retrieving the full Network instance (`account.getNetwork` was doing that). We will just store the network name. And we add a validation in `Wallet` constructor. 
Fixes #55. 
- Replacing instance of Network object to the string equivalent
- Updated fixtures to removed excessive objects not needed anymore
=> Refactorate : Usage of network object

src/Account/Account.js, src/Storage/Storage.js, src/Wallet/Wallet.js
`Wallet` constructor initialization requires method that are also available method of it's child. 
Therefore we use a prototype composition as first step. For consistency we did similar to Account, Wallet and Structure. 
Actually, with class expending, with that and dependencies loading (that eslint requires us to have on top of page), the real part of constructor file need scroling below. 
It could also get confusing to use Object.assign. 
Therefore we now just use it where it's immediately needed with a small comment on the why, and put the rest as the norms do (Class.prototoype.stuff = stuff) on bottom of file.
- Complying to norm
=> Style : Method composition refact

README.md
The service we use for badges have trouble recognizing badges for npm repo that are organization wide (@dashevo/...), therefore we had to rely on something else (github package.json reading)
- Remove coveralls badge (we do not use it)
- Fix Build link
- Use github reading instead of npm
=> Doc : Readme picto

src/plugins/Workers/SyncWorker.js
From DPW-885 we can learn that some issue have been found in the refresh process of the addresses and their balance. 
One of them was 10 minutes, which make no sense actually, either we are live and we use streams, either we are on demo and then hitting hard DAPI is not that much of an issue. 
- Introduce three threshold (fast, normal, slow). 
- Determine which address need to be fetch in regards of which threshold
Here is the logic : 
- Fast threshold (15 sec): Every address with unconfirmed balance. Five first unused address
-  Slow threshold (5 min): Address with exactly one tx that is >20000 ( 30days) block old (most likely once-used address that will see no refresh ever). 
All unused address except the first 10 (less likely to have any)
- Standard threshold (60 sec): Next 5 to 10 …
=> impr(SyncWorker): improve tx fetching

package-lock.json, package.json, src/types/Account/Account.d.ts, src/types/Account/Account.js, src/types/Account/methods/getIdentityPrivateKey.js, test/types/Account/getIdentityPrivateKey.js
Add a method to derive identity-specific keys to the `Account` class
Added a `getIdentityPrivateKey(number): PrivateKey` method to the `Account` class
Integration test added
=> feat: identity keys

.travis.yml
Right now, on each commit pushed to an open PR, 5 job get running, with two duplicate (node8 - test).
Let's clean up travis.yml with this PR.
Removed stages : `lint` and `test`, also remove before_test lint. 
Also removed `npm ci` as it's part of default too (see notes)
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#dependency-management
`If package-lock.json or npm-shrinkwrap.json exists and your npm version supports it, Travis CI will use npm ci instead of npm install.`
=> chore(travis): updated stages process

.eslintrc, examples/wallet-simple-example.js, package-lock.json, package.json
- `no-console` rule set off as soon as console statement is used literally everywhere
-  `dapi-client` updated to the latest version
-  `wallet-simple-example.js` fixed
=> chore: dependency update

docs/getting-started/quickstart.md, docs/usage/account.md, docs/usage/events.md, docs/usage/keychain.md, docs/usage/wallet.md, examples/wallet-dapi-fromHDPubKey.js, examples/wallet-dapi-porto-update.js, package-lock.json, package.json, src/CONSTANTS.js, src/index.d.ts, src/transports/Transporter.js, src/types/Account/Account.d.ts, src/types/Account/Account.js, src/types/Account/_initializeAccount.js, src/types/KeyChain/KeyChain.d.ts, src/types/KeyChain/KeyChain.js, src/types/KeyChain/methods/getHardenedBIP44Path.js, src/types/KeyChain/methods/getHardenedDIP9FeaturePath.js, src/types/Wallet/Wallet.d.ts, src/types/Wallet/Wallet.js, test/types/Account/Account.js, test/types/KeyChain/KeyChain.js, test/types/Storage/methods/startWorker.js
With Evonet being released, Wallet-lib and DashJS have their MVP feature-set release. 
This PR brings the last required changes for enabling interaction with Evonet. 
- feat: added getHardenedDIP9FeaturePath
- feat: added account.isReady() and account.isInitialiazed() for syntaxic helper around events.on('ready')
- DAPI connectivity with Evonet
- Renamed `keyChain.getHardenedPath` to `keyChain.getHardenedBIP44Path`
- impr: generate new mnemonic when {mnemonic:null} is provided. 
- doc: KeyChain typings required for usage on DashJS
This PR had it's requirement driven by the usage on DashJS. Close work and various manual tests were provided on top of our test suite.
Most of the changes toward grpc is being done by our use of DAPI-Client.
=> impr: evonet connectivity and related improvement

.travis.yml, scripts/travis-deploy.sh
Removed our GH_Token : This is not required anymore, nothing is private.
Added npm run build before npm publish and removing current dist/* folder
- Removed GH_TOKEN in .travis.yml
- Modified travis-deploy with npm run build
- Removed folder dist
We used this to require our private repo, we do not need that anymore as all repos are now public.
=> chore: travis build process

src/transporters/types/DAPIClient/methods/getUTXO.js, src/transporters/types/DAPIClient/methods/subscribeToAddressesTransactions.js, src/types/Account/methods/fetchAddressInfo.js, test/transporters/types/DAPIClient/methods/getUTXO.spec.js
In the rush of 6.0.0, we had to delay support for 1000 utxo based wallet. 
This brings back the support for those cases. 
- impr: parallelized requests to multiple dapi node for the different range (per 1000utxos)
- breaking: internal breaking change .transporter.getUTXO now only returns the utxos list (Object > Array[utxos])
=> fix: support for DAPIClient.getUTXO with more than 1000 utxos

src/types/Storage/methods/updateAddress.js, test/z-integrations/sweepWallet.js
With the removal of blockheight from block, we lost the ability to count the confirmation amount from a transaction. 
It had an effect on being able to pay in certains circonstances. 
This PR fixes that by always considering TX has spendable if they are in a block. 
We will need to take ClSig in consideration later on. 
- fix: assign balance to confirmedBalance for all tx 
We will need to add later on the verification for ClSig (chainlock)
=> fix: confirmedBalance always empty

.travis.yml
Currently PRs from external repos cannot successfully run tests because Travis prevents them from accessing the NPM token. In the same way, we do not need it in the before_install as we do not have any private repo anymore.
Only require npm on deployment.
This was used in dashevo/dapi-grpc#61 and  dashevo/dashjs#66. Expecting good results based on previous results there.
N/A
=> build: moved npm access_token from before_install to before_deploy

.travis.yml
Right now, when github request a build, due to our .travis.yml only accepting develop and master, any tags (v.x.x.x) would not be ran, and therefore we would not see it being deploy. 
This PR fixes that. 
- added regex for tags on `branches.only:`
N/A
N/A
=> build: allow travis build request on tags

src/plugins/StandardPlugin.js, src/transporters/types/BaseTransporter/BaseTransporter.js, src/types/Account/Account.js, src/types/Storage/Storage.js
In Wallet-lib eventemitter2 feature are not used, they are only for users. 
Sadly, in DashJS post-compile, we face a blocking issue with this library that blocks further release, and therefore we remove it.
- chore: removed eventemitter2
- Using test suite
- Users won't be able to use wildcard and delimiter feature of Events.
=> impr!: removed eventemitter2

src/types/Account/methods/broadcastTransaction.js, src/types/Account/methods/broadcastTransaction.spec.js
`broadcastTransaction` not throwing an error when a transaction wasn't broadcasted
Removed `try{} catch(){}` that was supressing the error
-
None
=> fix: broadcastTransaction not throwing an error when a transaction wasn't broadcasted

src/types/Storage/methods/insertIdentityAtIndex.js
When inserting a new identity at a specific index, we were resetting the identityIds array to empty array. 
This PR fixes that bug.
- fix: identityIds being restate to empty array
=> fix(Storage): identityIds being restate to empty array

src/plugins/Workers/BIP44Worker/ensureEnoughAddress.js, src/plugins/Workers/BIP44Worker/utils/getMissingIndexes.js, src/plugins/Workers/BIP44Worker/utils/isContiguousPath.js, src/types/Storage/methods/importTransaction.js
When we import a transaction and one of it's constitutive element (input or output) impact and address that we own but are not yet aware of it (because it exceed the BIP44 spec on first run, for instance on an index 21). 
We will submit for insertion again, but we where preventing any processing as we already had it. 
This PR fixes that issue. 
- refactored BIP44.ensureEnoughtAddress so utils are splitted in separate file
- ensure importTransaction re-process a transaction on addresses that are not marked as already having it (address.transactions[])
This specific case (us paying to ourself with a gap of address) were not included in test and will require to add it in our Tests improvement PR coming soon.
None.
=> fix: comportement on new address with existing transaction in store

src/types/Storage/methods/importTransaction.js, src/types/Storage/methods/importTransaction.spec.js
This is a bug not spotted by the test suite and introduced in #147, when if we were having the same address as input and output of the transactions, we would skip too early the process as we would have it market directly in the first run (on input)
We now only insert transaction hash in address store as the last part of the insertion process.
Added additional test that would highlight the problem if it happens again (and correctly break when tested on master).
None.
=> fix: transaction hash not present on address

docs/account/createTransaction.md, docs/getting-started/quickstart.md, src/types/Account/methods/createTransaction.js, src/types/Account/methods/createTransaction.spec.js
From PR #148. 
This PR fixes
- #145: createTransaction should be checking for `recipient` instead of `address` in `txOpts.recipients`
Changed checking property of 
`txOpts.recipients | Array[{address, satoshis}]` 
to
`txOpts.recipients | Array[{recipient, satoshis}]`
Manually by creating a valid transaction according to the documented `txOpts` via https://dashevo.github.io/wallet-lib/#/account/createTransaction
```
const transaction = account.createTransaction({
recipients: [
{recipient:'yT4FyAtrkpgnHviyMHe8NnbrVeH1EFVHFM',satoshis:10000}
]
});
```
Previously, the documentation stated a usage on createTransaction() with multiples recipients as such: recipients:[{recipient,satoshis}].
However the code where still referring and expecting recipients recipients:[{address,satoshis}].
This PR …
=> fix!: createTransaction should be checking for 'recipient' instead of 'address' in 'txOpts.recipients'

CHANGELOG.md, package-lock.json, package.json
**Notable Changes:**
- **Fixes:**  
* fix!: createTransaction should be checking for 'recipient' instead of 'address' in 'txOpts.recipients' ([#152](https://github.com/dashevo/wallet-lib/pull/152))
* fix: transaction hash not present on address ([#151](https://github.com/dashevo/wallet-lib/pull/151))
- **Breaking changes:**   
* Previously, the documentation stated a usage on `createTransaction()` with multiples recipients as such: `recipients:[{recipient,satoshis}]`.   
However, the code where still referring and expecting recipients `recipients:[{address,satoshis}]`.  
This version fixes that inconsistency.
=> chore(release): v7.13.3

src/types/Account/Account.js, src/types/Account/Account.spec.js
With a previous PR (https://github.com/dashevo/wallet-lib/pull/137) we removed eventemitter2, we used it's feature to broadcast all events in Account.js. 
We fixed an issue were the event were not forwarded.
Fixes https://github.com/dashevo/DashJS/issues/93.
- manually forward all events emitted by Storage.
- Added a test that ensure Account do forward event from storage using mocked Storage and single event (Blockheader)
N/A
=> fix(Account): forward all storage events

src/types/Account/Account.d.ts
When creating a transaction with a unique recipient, two parameters will need to be passed : 
- recipient, a PublicAddress
- satoshis or amount, a number. 
In our documentation we were referring to Recipient as a single object having an address, satoshis/amount.
This PR fixes that documentation issue.
- modified Account.d.ts to refer to the correct usage
- verified /docs/Account/createTransaction correctness
No code change.
N/A
=> fix: create transaction recipient documentation

src/types/Account/methods/getIdentityHDKeyByIndex.js, src/types/Account/methods/getIdentityHDKeyByIndex.spec.js
This PR resolve a compatibility issue in identity between iOS/Android and JS version. 
See DIP13 : https://github.com/dashpay/dips/blob/master/dip-0013.md#identity-authentication-keys 
- identityIndex of identity path is hardened
- modified test to match change
- previous identity created with DashJS / Wallet-lib would not be resolvable anymore
=> feat!: aligning identityIndex as defined in DIP13 as hardened 

.travis.yml, src/plugins/StandardPlugin.js, src/plugins/Worker.js, src/plugins/Workers/TransactionSyncStreamWorker/methods/startHistoricalSync.js, src/plugins/Workers/TransactionSyncStreamWorker/methods/startIncomingSync.js, src/types/Account/Account.js, src/types/Account/_initializeAccount.js, src/types/Account/methods/injectPlugin.js, src/types/Account/methods/injectPlugin.spec.js, src/types/Wallet/Wallet.js
In order to provide a better way to debug and handle errors that would be thrown on plugins, we need to provide more control and management of them.
- Wallet is now extending EventEmitter
- Account forwards errors to Wallet with arg 1 being the error and arg 2 referencing label, network and index of the account
- Plugin do not wrap errors but instead emit directly to Account their error conserving the stacktrace of the error
N/A
- Invalidate many of the previous wrapped errors (PluginFailedOnStart, ...)
=> feat: workers and plugins error handling using events

src/plugins/Workers/TransactionSyncStreamWorker/methods/getAddressesToSync.js, src/plugins/Workers/TransactionSyncStreamWorker/methods/getAddressesToSync.spec.js, src/types/Account/methods/getUTXOS.js, src/types/Account/methods/getUTXOS.spec.js
This fix https://github.com/dashevo/wallet-lib/issues/229 and might fix an issue on which we cannot sign the UTXO that we received from getUTXOS() therefore blocking creating/broadcasting some transaction.
This is specific to working with multiple account might it be during same runtime or using persistance (when on first runtime we would use account 0, and second runtime account 1). 
- filter HD wallet subscription path on TransactionStreamWorker.
- filter on getUTXO on HD Wallet.
- Further tests should be added in another PR to cover multiple account working with a TXStream. 
N/A
=> fix: UTXO being mixed up with multiple account in parallel

.github/workflows/test_and_release.yml
NPM tags were previously only `dev` or `latest`, this should now be changed to the `major.minor-dev` format for dev tags.
- add semver dependency
- use semver to parse proper tag and pass to NPM release step
Tested with js-dpp repo
None
=> chore(ci): npm tags should be formatted major.minor-dev

docs/identities/getIdentityHDKeyByIndex.md
method description for getIdentityHDKeyByIndex is outdated, this PR updates the description for the current interface closes #244
=> docs: fix method description for getIdentityHDKeyByIndex

docs/_sidebar.md, docs/keychain/getHardenedBIP44HDKey.md, docs/keychain/getHardenedDIP9FeatureHDKey.md, src/types/Identities/methods/getIdentityHDKeyByIndex.js, src/types/KeyChain/KeyChain.d.ts, src/types/KeyChain/KeyChain.js, src/types/KeyChain/KeyChain.spec.js, src/types/KeyChain/methods/getHardenedBIP44HDKey.js, src/types/KeyChain/methods/getHardenedDIP9FeatureHDKey.js
This breaking change PR bring a small naming update, indeed we had getHardenedBIP44Path and getDIP9FeaturePath methods that directly returns keys. 
As naming is documentation by itself, this modification will better reflect expected comportment of those methods. 
- renamed getHardenedBIP44Path to getHardenedBIP44HDKey
- renamed getHardenedDIP9FeaturePath to getHardenedDIP9FeatureHDKey
- added missing test for getHardenedDIP9FeatureHDKey
- Added new test
-  `getHardenedBIP44Path` renamed to `getHardenedBIP44HDKey`
- `getHardenedDIP9FeaturePath` renamed to  `getHardenedDIP9FeatureHDKey`
=> refactor(Keychain)!: proper naming for BIP44 and DIP9 get keys methods
