dashevo/wallet-lib

- .travis.yml
This should prevent out-of-sync issues between package and lock files.
> Use npm ci in Travis instead of install

- package-lock.json
- package.json
> Apply results of npm audit fix

- package-lock.json
- test/Account/getTransactionHistory.js
One of the business requirement of Wallet-lib is to be able to perform getTransactionHistory in less than a second. 
- Added time based check
> Test : Add time requirement on getTransactionHistory

- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/pull_request_template.md
Creating a basic structure for our pull request & issues
- Added a template that should be picked up by github on new pr creation
- Added a basic issue template too
> doc(templates): Created basic template structure for PR and Issues

- index.js
- package.json
- src/index.d.ts
- src/types/Account/Account.d.ts
- src/types/Wallet/methods/Wallet.d.ts
Fixing TypeScript definitions
- Updating existing def with missing or broken attributes (optional,..)
> fix: definition fix

- .travis.yml
Added auto-deploy to npm on merges to master
Added deploy task to Travis
Hasn't been tested, as the merge is required
> feat: Add deploy task to travis

- .travis.yml
- package-lock.json
- package.json
- scripts/travis-deploy.sh
Added better deploy script that will deploy lib only if tests are run on the latest LTS version
Added the bash script to run deploy
Added the task to Travis config
> Feat: better deploy script

- examples/adapters/JSONStore.js
- package-lock.json
- package.json
- src/types/Account/Account.js
- src/types/Account/_initializeAccount.js
- src/types/Account/bls.js
- src/types/Account/methods/encode.js
- src/types/Account/methods/encrypt.js
- test/types/Account/encode.js
- test/types/Account/encrypt.js
- test/types/Storage/startWorker.js
BLS encryption - AES
```bash
npm test
```
```js
const extPubKey = account.keyChain.getKeyForPath(derivationPath, 'HDPublicKey');
const encryptedExtPubKey = account.encrypt(extPubKey, secret);
```
> BLS encryption AES256

- src/types/KeyChain/methods/sign.js
- test/types/Account/methods/sign.js
Simple support for "sign" to allow taking a Message contructor.
- Added Message to allowed constructor, returns a Message instance instead of str value. 
Added additional test for signing / verifying message.
> feat: added signing message support

- src/transporters/methods/resolve.js
- src/transporters/types/BaseTransporter/BaseTransporter.js
- src/transporters/types/BaseTransporter/methods/getBestBlock.js
- src/transporters/types/BaseTransporter/methods/getBestBlockHeader.js
- src/transporters/types/DAPIClient/DAPIClient.js
- src/transporters/types/DAPIClient/methods/getBestBlock.js
- src/transporters/types/DAPIClient/methods/getBestBlockHeader.js
- test/transporters/types/DAPIClient/methods/getBestBlock.spec.js
- test/transporters/types/DAPIClient/methods/getBestBlockHeader.spec.js
This PR is about adding .getBestBlock and .getBestBlockHeader as helpers for the transporter. 
- feat: added .getBestBlock
- feat: added .getBestBlockHeader
Sone new unit test were added to cover that implementation
> feat(Transporter): added .getBestBlock and .getBestBlockHeader

- package-lock.json
- package.json
- src/transporters/methods/resolve.js
In order to allow users to connect to the new endpoint and to resolve some accessibility issue to the seeds from outside, we bring in this PR additional PR. 
- fix: removed previous seeds (seed.evonet.networks...)
- fix: added new seeds dns (seed-1, ..., seed-5.evonet.networks...).
Successful integration tests means a proper resolving on those seeds. 
Also manual testing.
> fix: update evonet seeds

- examples/workers/ColdStorageWorker.js
- src/plugins/Plugins/ChainPlugin.js
- src/plugins/Worker.js
- src/transporters/methods/resolve.js
- src/transporters/types/DAPIClient/methods/getUTXO.js
- src/types/Account/Account.js
- src/types/Account/_initializeAccount.js
- src/types/Account/methods/broadcastTransaction.js
- src/types/Account/methods/createTransaction.js
- src/types/Account/methods/fetchAddressInfo.js
- src/types/Account/methods/getBlockHeader.js
- src/types/Account/methods/getTransaction.js
- src/types/Account/methods/injectPlugin.js
- src/types/Storage/_configureAdapter.js
- src/types/Storage/methods/saveState.js
- src/types/Storage/methods/updateAddress.js
- src/types/Wallet/methods/sweepWallet.js
- src/utils/coinSelections/TransactionEstimator.js
This PR removes some logged errors and improved the Error message that is being thrown at the users.
- style: removed many logger.error
- style: improved the message that is thrown to the user on failure. 
Relying on current test suite.
> style: removed logger.error & improved error message

- CHANGELOG.md
- package-lock.json
- package.json
Release Wallet Lib 7.1.0
Updated changelog and bumped version in package config.
None.
None.
> chore(release): update changelog and bump version to 7.1.0

- CHANGELOG.md
- package-lock.json
- package.json
**Notable Changes:**
- **Fixes:**
* fix(Storage): identityIds being restate to empty array (#143)
> chore(release): v7.13.1

- CHANGELOG.md
- package-lock.json
- package.json
Release `7.13.4`
Update changelog and bump version to `7.13.4`
With tests
None
> chore(release): update changelog and bump version to `7.13.4`

- .github/PULL_REQUEST_TEMPLATE.md
Since milestones are now used in this repo, they are being added to the PR template checklist
Add milestone checklist item
N/A
N/A
> chore: add milestone to PR template

- .travis.yml
- tests/functional/wallet.js
To be independent of the network and be able to easily test new changes on the network, we want to run tests against mn-bootstrap instead of the live network.
Modified Travis script to run mn-bootstrap
Travis builds
None
> feat: run tests against mn-bootstrap instead of devnet

- package-lock.json
- package.json
- src/types/Wallet/Wallet.d.ts
Update DAPI Client to v0.14.0-dev.8
* Updated DAPI Client
* Updated DAPIClientOptions definition
Unit tests
The DAPI Client option `addresses` renamed to `dapiAddresses`
> feat!: update dapi-client to 0.14.0-dev.8

- src/types/Wallet/Wallet.d.ts
- src/types/types.d.ts
To test DashJs against platform-test-suite we need to add support more network values.
Add more possible values to network option type
Unit tests
None
> fix: outdated network option values

- package-lock.json
- package.json
Bumped version to 7.14.0-dev.2
Unit tests
None
> chore: bump version to 7.14.0-dev.2

- CHANGELOG.md
- package-lock.json
- package.json
Release 7.14.0
Updated changelog and bumped package version to 7.14.0
With tests
None
> chore(release): update changelog and bump version to 7.14.0

- package-lock.json
- package.json
dapi-client updated to 0.15.0-dev.1
Unit tests
None
> feat: update dapi-client to 0.15.0-dev.1

- package-lock.json
- package.json
Version bumped to 7.15.0-dev.1
Unit tests
None
> chore: bump version to 7.15.0-dev.1

- package-lock.json
- package.json
Need to update dashcore-lib to 0.19.2
dashcore-lib updated to 0.19.2, dapi-client updated to 0.15.0-dev.3
Unit tests
None
> feat: update dapi-client to 0.15.0-dev.4

- package-lock.json
- package.json
Version bumped to 7.15.0-dev.2
Unit tests
None
> chore: bump version to 7.15.0-dev.2

- package-lock.json
- package.json
Updated `dapi-client`
Updated `dapi-client`
> feat: update dapi-client to 0.15.0-dev.6

- package-lock.json
- package.json
Updated version
Updated version
> chore: bump version to 7.15.0-dev.4

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): update changelog and bump version to 7.15.1

- docs/develop/logging.md
- docs/develop/persistence.md
- docs/getting-started/core-concepts.md
- docs/getting-started/quickstart.md
- docs/plugins/community-plugins.md
- docs/plugins/using-a-plugin.md
- docs/plugins/wallet-workers.md
- docs/plugins/writing-a-new-plugin.md
- docs/storage/importTransaction.md
- docs/storage/importTransactions.md
- docs/usage/coinSelection.md
- docs/usage/examples.md
- package-lock.json
- src/errors/InvalidDashcoreTransaction.js
- src/plugins/Worker.spec.js
- src/types/Account/methods/sign.js
- src/types/Account/methods/sign.spec.js
- src/types/Storage/methods/importTransaction.js
- src/types/Storage/methods/importTransaction.spec.js
- allow .sign() method to auto-sign transaction based on inputs.
- allow importTransaction() to import JSON based data
- allow .sign() to handle cases with OP_RETURN (#160)
Added provided tests
N/A
> fix: transaction sign and OP_RETURN + import

- package-lock.json
- package.json
Update dapi-client to 0.16
Updated package and package-lock files
Run the tests
None
> chore: update dapi-client

- package-lock.json
- package.json
Version bump
Bumped the version in the package files
None
> chore: version-bump

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 7.16.0-dev.2

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 7.17.0-dev.1

- package-lock.json
- package.json
update `dpp`, `dapi-client`, `dashcore-lib`
update `dpp`, `dapi-client`, `dashcore-lib`
> feat: update `dpp`, `dapi-client`, `dashcore-lib`

- package-lock.json
- package.json
bump version to 7.17.0-dev.4
bump version to 7.17.0-dev.4
> chore: bump version to 7.17.0-dev.4

- docs/storage/createWallet.md
- docs/wallet/Wallet.md
- package-lock.json
- package.json
- src/types/Wallet/Wallet.js
Connect to testnet by default
Use new DAPI Client and testnet network option by default
With tests
Connects to testnet by default
> feat!: connect to testnet by default

- package-lock.json
- package.json
Fixing an issue in dashcore-lib: merkleRootQuorums from the diff doesn’t match calculated quorum root after diff is applied
- Updated `dashcore-lib`
On testnet.
None.
> fix: merkleRootQuorums from the diff doesn’t match calculated quorum root after diff is applied

- CHANGELOG.md
- package-lock.json
- package.json
Updating to v17.1
- Updated changelog
- Bumped version
None.
None.
> chore(release): update changelog and bump version 0.17.1

- package-lock.json
- package.json
broadcastStateTransition is timing out on testnet and larger networks
- updated `dapi-client` with a fix
Tests.
None.
> fix: broadcastStateTransition is timing out on testnet

- CHANGELOG.md
- package-lock.json
- package.json
Release 0.17.2
- Updated changelog
- Bump version
None
None
> chore(release): update changelog and bump version to 0.17.2

- src/plugins/Workers/TransactionSyncStreamWorker/TransactionSyncStreamWorker.js
- src/test/mocks/createAndAttachTransportMocksToWallet.js
- src/types/Wallet/Wallet.d.ts
- src/types/Wallet/Wallet.js
- tests/integration/plugins/Workers/TransactionSyncStreamWorker.spec.js
Adding an unsafe option to skip number of blocks on initial sync as per #216 
- added `unsafeOptions` namespace
- added `skipSynchronizationBeforeHeight` option
Unit tests.
None.
> feat: add `skipSynchronizationBeforeHeight` unsafe option

- package-lock.json
- package.json
Bumped version
Unit tests
None
> chore: bump version to 7.18.0-dev.2

- package-lock.json
- package.json
DPP now uses `verifyInstantLock` method of State Repository that updated ensures it is propagated everywhere
- updated `dpp` dependency
Local node setup
None.
> feat: update dpp with verifyInstantLock method

- .travis.yml
- README.md
- package-lock.json
- package.json
Bump version
Bump version
None.
> chore: bump version to 7.19.0-dev.1

- .github/workflows/test_and_release.yml
Minor renaming and refactoring
- Rename one step
- Remove unnecessary input
> chore(ci): github actions rename

- .github/workflows/.env
- .github/workflows/test_and_release.yml
- .gitignore
Pass dependencies with variables through PR body is not convenient since they won't be avaialble for release and upcomming PRs 
- Load variables from workflows dotenv file
With CI
None
> chore(ci): load variables for dotenv file

- package-lock.json
- package.json
> chore: bump version to 7.18.1

- .github/workflows/.env
- CHANGELOG.md
- package-lock.json
- package.json
Release 7.19.0
- Update changelog
- Bump version to 7.19.0
None
None
>  chore(release): update changelog and bump version 7.19.0

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): v7.19.1

- docs/_sidebar.md
- docs/account/getTransactionHistory.md
- docs/account/getTransactions.md
> docs: getTransactions

- .github/workflows/test_and_release.yml
- package-lock.json
- package.json
- src/transport/DAPIClientTransport/methods/getTransaction.js
> fix: Identifier expects Buffer

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): wallet-lib v0.19.2

- src/types/Account/Account.d.ts
> fix: add encrypt  type, fix decrypt type for Account

- package-lock.json
- package.json
The version was bumped to 7.20.0-dev.2
- [xshu] I have performed a self-review of my own code
> chore: bump version to 7.20.0-dev.2

- src/types/Account/Account.d.ts
- src/types/Account/Account.js
- src/types/Wallet/Wallet.d.ts
- src/types/Wallet/Wallet.js
We want to set default timeout for `waitForInstantLock` method
New waitForInstantLockTimeout account option introduced
No
> feat: add waitForInstantLockTimeout Account Option

- .github/workflows/.env
- package-lock.json
- package.json
The version was bumped to 7.20.0-dev.3
No
> chore(release): bump version to 7.20.0-dev.3

- .github/workflows/test_and_release.yml
CI was failing with `[FAILED] Docker Compose V2 is not installed` due to an update in `gh-action-start-local-network`
- Add compose v2 installation step
- Delete unused variables
in CI
> chore(ci): satisfy new compose v2 dependency

- .github/workflows/test_and_release.yml
The satackey cache action does not give appreciable benefits when not building our own images.
- Remove satackey cache action
In CI
> chore(ci): remove satackey cache action

- .github/workflows/test_and_release.yml
If branches are specified, dashmate will build them, slowing down CI. CI was also showing warning `Unexpected input(s) 'actions-cache-url', 'actions-cache-token'`
- Remove unused cache vars
- Add buildkit caching
In CI
None
> build: use docker BuildKit cache

- package-lock.json
- package.json
We need to bump version before release
The version was bumped up to 7.20.0-dev.4
With tests
None
> chore: bump version to 7.20.0-dev.4

- CHANGELOG.md
- package-lock.json
- package.json
Release 7.20.1
- Update changelog
- Bump version to 7.20.1
None
None
> chore(release): update changelog and bump version 7.20.1

- package-lock.json
- package.json
> chore: bump version to 7.21.0-dev.1

- src/types/Account/Account.d.ts
This small typing fix should resolves https://github.com/dashevo/js-dash-sdk/issues/185
- fix: typing issue for waitForInstantLock
N/A
N/A
> fix: typings fix for waitForInstantLock

- src/types/Account/Account.d.ts
This fixes #254 
Implements TS specification for identities property in account.
N/A
N/A
> docs(Account): added identities ts specs
